#!/usr/bin/env sh

python scrape.py ANTH "Anthropology" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5517 > json/anthropology.json
python scrape.py ARCH "Archaeology" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5543 > json/archaeology.json
python scrape.py ARTS "Arts" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5641 > json/arts.json
python scrape.py CLAS "Classics" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5649 > json/classics.json
python scrape.py CMST "Communication Studies" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5731 > json/communicationstudies.json
python scrape.py ECON "Economics" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5756 > json/economics.json
python scrape.py ENGL "English" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5821 > json/english.json
python scrape.py ENSL "English as a Second Language" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-5998 > json/englishasasecondlanguage.json
python scrape.py FOLK "Folklore" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6008 > json/folklore.json
python scrape.py FREN "French" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6082 > json/french.json
python scrape.py GNDR "Gender Studies" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6938 > json/genderstudies.json
python scrape.py GEOG "Geography" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6145 > json/geography.json
python scrape.py GERM "German" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6208 > json/german.json
python scrape.py HIST "History" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6287 > json/history.json
python scrape.py LWSO "Law and Society" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6416 > json/lawandsociety.json
python scrape.py LING "Linguistics" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6432 > json/linguistics.json
python scrape.py MST "Medieval Studies" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6512 > json/medievalstudies.json
python scrape.py PHIL "Philosophy" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6527 > json/philosophy.json
python scrape.py PLST "Police Studies" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6620 > json/policestudies.json
python scrape.py POSC "Political Science" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6631 > json/politicalscience.json
python scrape.py RELS "Religious Studies" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6712 > json/religiousstudies.json
python scrape.py SOCI "Sociology" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-6805 > json/sociology.json
python scrape.py UNIV "University" http://www.mun.ca/regoff/calendar/sectionNo\=ARTS-7313 > json/university.json
python scrape.py BUSI "Business Services" http://www.mun.ca/regoff/calendar/sectionNo\=BUSI-1261\#BUSI-0283 > json/businessservicecourses.json
python scrape.py BUSI "Business Core and Elective Courses" http://www.mun.ca/regoff/calendar/sectionNo\=BUSI-0288 > json/businesscoreandelectivecourses.json
python scrape.py BUSI "Business Work Terms" http://www.mun.ca/regoff/calendar/sectionNo\=BUSI-0401 > json/businessworkterms.json
python scrape.py BUSI "Business Case Analysis" http://www.mun.ca/regoff/calendar/sectionNo\=BUSI-0419 > json/businesscaseanalysis.json
python scrape.py ED "Education" http://www.mun.ca/regoff/calendar/sectionNo\=EDUC-0443 > json/education.json
python scrape.py ENGI "Engineering Work Terms" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0037\#ENGI-0495 > json/engineeringworkterms.json
python scrape.py ENGI "Engineering One" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0504 > json/engineeringone.json
python scrape.py ENGI "Engineering Term Three" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0517 > json/engineeringtermthree.json
python scrape.py ENGI "Engineering Term Four" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0534 > json/engineeringtermfour.json
python scrape.py ENGI "Engineering Term Five" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0554 > json/engineeringtermfive.json
python scrape.py ENGI "Engineering Term Six" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0578 > json/engineeringtermsix.json
python scrape.py ENGI "Engineering Term Seven" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0605 > json/engineeringtermseven.json
python scrape.py ENGI "Engineering Term Eight" http://www.mun.ca/regoff/calendar/sectionNo\=ENGI-0643 > json/engineeringtermeight.json
python scrape.py MSTM "Marine Studies and Technology Management"
http://www.mun.ca/regoff/calendar/sectionNo\=MARINE-0149 > json/marinestudiesandtechnologymanagement.json
python scrape.py HKR "Human Kinetics and Recreation" http://www.mun.ca/regoff/calendar/sectionNo\=HKR-0366 > json/humankineticsandrecreation.json
python scrape.py MED "Medical Studies" http://www.mun.ca/regoff/calendar/sectionNo\=MED-0376 > json/medicalstudies.json
python scrape.py MED "Medicine Courses for Non-Medical Students" http://www.mun.ca/regoff/calendar/sectionNo\=MED-0401 > json/nonmedicalcourses.json
python scrape.py NURS "Nursing" http://www.mun.ca/regoff/calendar/sectionNo\=NURS-0230 > json/nursing.json
python scrape.py PHAR "Pharmasy" http://www.mun.ca/regoff/calendar/sectionNo\=PHAR-0126 > json/pharmacy.json
python scrape.py SCWK "Social Work" http://www.mun.ca/regoff/calendar/sectionNo\=SCWK-0130 > json/socialwork.json
python scrape.py BIOC "Biochemistry" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-2563 > json/biochemistry.json
python scrape.py BIOL "Biology" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-0766 > json/biology.json
python scrape.py CHEM "Chemistry" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-0905 > json/chemistry.json
python scrape.py COMP "Computer Science" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-1023 > json/computerscience.json
python scrape.py EASC "Earth Sciences" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-2273 > json/earthsciences.json
python scrape.py MATH "Mathematics and Statistics" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-1331 > json/mathandstats.json
python scrape.py OCSC "Ocean Sciences" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-3569 > json/oceansciences.json
python scrape.py PHYS "Physics and Physical Oceanography" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-1574 > json/physicsandoceanography.json
python scrape.py PSYC "Psychology" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-1702 > json/psychology.json
python scrape.py SCI "Science" http://www.mun.ca/regoff/calendar/sectionNo\=SCI-2554 > json/science.json
